/**
 * @leela/content — the texts of the game: 72 plans and the rules chapters,
 * merged from four repositories into one dataset.
 *
 * The JSON under `data/` is generated by `scripts/build-content.mjs`. Do not
 * hand-edit it; edit the source repository and rebuild, or move the source of
 * truth in here and retire the generator.
 */

import { TOTAL_PLANS } from '@leela/engine';

export interface Plan {
  /** 1..72 */
  plan: number;
  /** Plan name with any leading numbering removed. */
  title: string;
  /** One-paragraph summary, when the source had one. */
  description: string | null;
  /** Full text. */
  body: string;
  /** Where this text came from, for provenance. */
  source: string;
}

export interface RuleChapter {
  slug: string;
  title: string | null;
  body: string;
  source: string;
}

/** Languages the dataset covers, as BCP-47 primary subtags. */
export const LANGUAGES = [
  'ar', 'bn', 'de', 'en', 'es', 'fr', 'hi', 'ja', 'jv', 'ko', 'mr',
  'ms', 'pa', 'pt', 'ru', 'ta', 'te', 'tr', 'uk', 'ur', 'vi', 'zh',
] as const;

export type Language = (typeof LANGUAGES)[number];

/** The language to fall back to when a request cannot be served. */
export const FALLBACK_LANGUAGE: Language = 'en';

export function isLanguage(value: string): value is Language {
  return (LANGUAGES as readonly string[]).includes(value);
}

/**
 * Resolve a locale like `ru-RU`, `zh-Hans` or `en_GB` onto a covered language,
 * falling back to English.
 */
export function resolveLanguage(locale: string | undefined | null): Language {
  if (!locale) return FALLBACK_LANGUAGE;
  const [primary = ''] = locale.toLowerCase().split(/[-_]/);
  return isLanguage(primary) ? primary : FALLBACK_LANGUAGE;
}

// The dataset is bundled as JSON so every runtime — Metro, Node, the browser —
// can load it without a filesystem.
import ar from '../data/plans.ar.json';
import bn from '../data/plans.bn.json';
import de from '../data/plans.de.json';
import en from '../data/plans.en.json';
import es from '../data/plans.es.json';
import fr from '../data/plans.fr.json';
import hi from '../data/plans.hi.json';
import ja from '../data/plans.ja.json';
import jv from '../data/plans.jv.json';
import ko from '../data/plans.ko.json';
import mr from '../data/plans.mr.json';
import ms from '../data/plans.ms.json';
import pa from '../data/plans.pa.json';
import pt from '../data/plans.pt.json';
import ru from '../data/plans.ru.json';
import ta from '../data/plans.ta.json';
import te from '../data/plans.te.json';
import tr from '../data/plans.tr.json';
import uk from '../data/plans.uk.json';
import ur from '../data/plans.ur.json';
import vi from '../data/plans.vi.json';
import zh from '../data/plans.zh.json';
import rulesData from '../data/rules.json';

const PLANS: Record<Language, Plan[]> = {
  ar, bn, de, en, es, fr, hi, ja, jv, ko, mr,
  ms, pa, pt, ru, ta, te, tr, uk, ur, vi, zh,
} as Record<Language, Plan[]>;

const RULES = rulesData as Record<string, RuleChapter[]>;

/** Every plan for a language, ordered 1..72. */
export function plansFor(locale: string): Plan[] {
  return PLANS[resolveLanguage(locale)];
}

/**
 * One plan by number.
 *
 * @throws RangeError when `plan` is outside 1..72.
 */
export function planFor(locale: string, plan: number): Plan {
  if (!Number.isInteger(plan) || plan < 1 || plan > TOTAL_PLANS) {
    throw new RangeError(`plan must be an integer in 1..${TOTAL_PLANS}, got ${plan}`);
  }
  const language = resolveLanguage(locale);
  const found = PLANS[language].find((p) => p.plan === plan);
  // Every language is complete, but fall back rather than throw if a future
  // rebuild ever drops one.
  return found ?? (PLANS[FALLBACK_LANGUAGE].find((p) => p.plan === plan) as Plan);
}

/** Rules chapters for a language, empty when none were translated. */
export function rulesFor(locale: string): RuleChapter[] {
  return RULES[resolveLanguage(locale)] ?? RULES[FALLBACK_LANGUAGE] ?? [];
}

/** One rules chapter by slug, or null. */
export function ruleChapter(locale: string, slug: string): RuleChapter | null {
  return rulesFor(locale).find((c) => c.slug === slug) ?? null;
}

// What a language is, beyond its texts: which way it reads, what it calls
// itself, and how to keep a diagram from being reordered by a reader's script.
export {
  LANGUAGE_NAMES,
  asLeftToRight,
  couldBe,
  directionOf,
  dominantScript,
  scriptOf,
} from './languages';
export type { Script } from './languages';

// The sentences the game says about itself, as opposed to the text it teaches.
// Kept in a second file because the catalogue is prose and this one is data.
export {
  englishCatalogue,
  messageCoverage,
  messageFor,
  messageIssues,
  placeholdersIn,
  translatedLanguages,
  type LanguageCoverage,
  type Message,
  type MessageIssue,
  type MessageKey,
  type MessageParams,
  type PluralForms,
} from './messages';
