/**
 * @leela/content — the texts of the game: 72 plans and the rules chapters,
 * merged from four repositories into one dataset.
 *
 * The JSON under `data/` is generated by `scripts/build-content.mjs`. Do not
 * hand-edit it; edit the source repository and rebuild, or move the source of
 * truth in here and retire the generator.
 */

import { TOTAL_PLANS } from '@leela/engine';

export interface Plan {
  /** 1..72 */
  plan: number;
  /** Plan name with any leading numbering removed. */
  title: string;
  /** One-paragraph summary, when the source had one. */
  description: string | null;
  /** Full text. */
  body: string;
  /** Where this text came from, for provenance. */
  source: string;
}

export interface RuleChapter {
  slug: string;
  title: string | null;
  body: string;
  source: string;
  /**
   * True when this chapter is not in the reader's language.
   *
   * Set by `bookFor` when a language's book is missing a chapter every other
   * book has. Carried rather than hidden: a reader is owed the difference
   * between "written for you" and "the only copy there is".
   */
  borrowed?: boolean;
}

// What a language is, before any text exists — the list, the type, the fallback
// and how to resolve a locale. In a leaf of its own because `messages.ts` needs
// those four and this file re-exports `messages.ts`: the two required each
// other, and Metro warned about it on every launch of the phone app.
export {
  FALLBACK_LANGUAGE,
  isLanguage,
  LANGUAGES,
  resolveLanguage,
  type Language,
} from './language';
import { FALLBACK_LANGUAGE, resolveLanguage, type Language } from './language';

// The dataset is bundled as JSON so every runtime — Metro, Node, the browser —
// can load it without a filesystem.
import ar from '../data/plans.ar.json';
import bn from '../data/plans.bn.json';
import de from '../data/plans.de.json';
import en from '../data/plans.en.json';
import es from '../data/plans.es.json';
import fr from '../data/plans.fr.json';
import hi from '../data/plans.hi.json';
import ja from '../data/plans.ja.json';
import jv from '../data/plans.jv.json';
import ko from '../data/plans.ko.json';
import mr from '../data/plans.mr.json';
import ms from '../data/plans.ms.json';
import pa from '../data/plans.pa.json';
import pt from '../data/plans.pt.json';
import ru from '../data/plans.ru.json';
import ta from '../data/plans.ta.json';
import te from '../data/plans.te.json';
import tr from '../data/plans.tr.json';
import uk from '../data/plans.uk.json';
import ur from '../data/plans.ur.json';
import vi from '../data/plans.vi.json';
import zh from '../data/plans.zh.json';
import rulesData from '../data/rules.json';

const PLANS: Record<Language, Plan[]> = {
  ar, bn, de, en, es, fr, hi, ja, jv, ko, mr,
  ms, pa, pt, ru, ta, te, tr, uk, ur, vi, zh,
} as Record<Language, Plan[]>;

const RULES = rulesData as Record<string, RuleChapter[]>;

/** Every plan for a language, ordered 1..72. */
export function plansFor(locale: string): Plan[] {
  return PLANS[resolveLanguage(locale)];
}

/**
 * One plan by number.
 *
 * @throws RangeError when `plan` is outside 1..72.
 */
export function planFor(locale: string, plan: number): Plan {
  if (!Number.isInteger(plan) || plan < 1 || plan > TOTAL_PLANS) {
    throw new RangeError(`plan must be an integer in 1..${TOTAL_PLANS}, got ${plan}`);
  }
  const language = resolveLanguage(locale);
  const found = PLANS[language].find((p) => p.plan === plan);
  // Every language is complete, but fall back rather than throw if a future
  // rebuild ever drops one.
  return found ?? (PLANS[FALLBACK_LANGUAGE].find((p) => p.plan === plan) as Plan);
}

/** Rules chapters for a language, empty when none were translated. */
export function rulesFor(locale: string): RuleChapter[] {
  return RULES[resolveLanguage(locale)] ?? RULES[FALLBACK_LANGUAGE] ?? [];
}

/**
 * The book a reader gets, which is never empty.
 *
 * A language with no chapters is served English — as a *whole book*, not
 * chapter by chapter: half in one language and half in another is worse than
 * one a reader can at least read.
 *
 * This was written out five times: twice in the bot, twice in the mini app,
 * and its absence once in the docs. Four of those five were written in a single
 * afternoon, by one author, which is how quickly a rule spreads once it lives
 * nowhere.
 *
 * **The docs deliberately do not use it.** `apps/docs` writes a page per
 * language per chapter, and `audit-dataset.mjs` refuses a chapter written in a
 * script its language does not use — a published `/de/rules/notes.html` holding
 * English would be exactly that. A reader shown English on screen has been
 * helped; a reader handed a German URL serving English has been misled. The
 * difference is between falling back and filing wrongly.
 */
export function bookFor(locale: string): RuleChapter[] {
  return bookFrom(rulesFor(locale), rulesFor(FALLBACK_LANGUAGE));
}

/**
 * The borrow rule, over two books rather than over the whole dataset.
 *
 * `bookFor` reads `RULES`, which is every language at once — right for a server
 * and wrong for a phone, where fetching the book means fetching one language's
 * chapters and English's. A surface that has loaded exactly those two still has
 * to make the same decision about them, and a decision made twice is a decision
 * that will differ: this is the one place it is written.
 *
 * Takes no locale on purpose. Which chapters belong to whom is the caller's
 * business; what to do when one book is short is this function's.
 */
export function bookFrom(
  chapters: readonly RuleChapter[],
  english: readonly RuleChapter[],
): RuleChapter[] {
  if (chapters.length === 0) return [...english];

  // A chapter the reader's book does not have, borrowed from English and
  // marked as borrowed.
  //
  // The whole-book rule above is about a language with *nothing*, and it is
  // still right. This is a different situation and it was found rather than
  // imagined: Ukrainian, Malay and Arabic carry `online` and `foreword` — a
  // chat-moderation policy and a preface — and no chapter on the chakras,
  // because those three came through a different donor with a different table
  // of contents. Two of them have no `meaning` chapter either.
  //
  // So the choice was never "one language or two". It was "the chapter in
  // English, or no chapter at all", and a reader cannot read what is not
  // there. The order is the reader's own book first, then whatever it is
  // missing, so nothing they *do* have is displaced.
  const have = new Set(chapters.map((chapter) => chapter.slug));
  const missing = english
    .filter((chapter) => !have.has(chapter.slug))
    .map((chapter) => ({ ...chapter, borrowed: true }));

  return [...chapters, ...missing];
}

/** One rules chapter by slug, or null. */
export function ruleChapter(locale: string, slug: string): RuleChapter | null {
  return rulesFor(locale).find((c) => c.slug === slug) ?? null;
}

// A move, in a sentence. Beside the catalogue it is built from, because two
// surfaces need the same nine sentences and a tenth would be a tenth wording.
export { describeMove } from './describe';
export type { TitleOf } from './describe';

// What a language is, beyond its texts: which way it reads, what it calls
// itself, and how to keep a diagram from being reordered by a reader's script.
export {
  LANGUAGE_NAMES,
  asLeftToRight,
  couldBe,
  directionOf,
  dominantScript,
  scriptOf,
  writtenIn,
} from './languages';
export type { Script } from './languages';

// The sentences the game says about itself, as opposed to the text it teaches.
// Kept in a second file because the catalogue is prose and this one is data.
export {
  englishCatalogue,
  messageCoverage,
  messageFor,
  messageIssues,
  placeholdersIn,
  translatedLanguages,
  type LanguageCoverage,
  type Message,
  type MessageIssue,
  type MessageKey,
  type MessageParams,
  type PluralForms,
} from './messages';
