/**
 * @leela/content — the texts of the game: 72 plans and the rules chapters,
 * merged from four repositories into one dataset.
 *
 * The JSON under `data/` is generated by `scripts/build-content.mjs`. Do not
 * hand-edit it; edit the source repository and rebuild, or move the source of
 * truth in here and retire the generator.
 */

import { TOTAL_PLANS } from '@leela/engine';

export { FREE_MOVES, SUBSCRIBE_REQUEST } from './access';

export interface Plan {
  /** 1..72 */
  plan: number;
  /** Plan name with any leading numbering removed. */
  title: string;
  /** One-paragraph summary, when the source had one. */
  description: string | null;
  /** Full text. */
  body: string;
  /** Where this text came from, for provenance. */
  source: string;
}

export interface RuleChapter {
  slug: string;
  title: string | null;
  body: string;
  source: string;
  /**
   * True when this chapter is not in the reader's language.
   *
   * Set by `bookFor` when a language's book is missing a chapter every other
   * book has. Carried rather than hidden: a reader is owed the difference
   * between "written for you" and "the only copy there is".
   */
  borrowed?: boolean;
}

// What a language is, before any text exists — the list, the type, the fallback
// and how to resolve a locale. In a leaf of its own because `messages.ts` needs
// those four and this file re-exports `messages.ts`: the two required each
// other, and Metro warned about it on every launch of the phone app.
export {
  FALLBACK_LANGUAGE,
  isLanguage,
  LANGUAGES,
  resolveLanguage,
  type Language,
} from './language';
import { FALLBACK_LANGUAGE, resolveLanguage, type Language } from './language';

// The dataset is JSON so every runtime — Metro, Node, the browser — can load it
// without a filesystem. English is imported; the other twenty-one are not, and
// {@link LOADERS} below says why.
import en from '../data/plans.en.json';
import rulesData from '../data/rules.json';

/**
 * The twenty-one languages that are not English, each behind a thunk.
 *
 * They used to be twenty-one more `import` lines, and the cost was paid by
 * every reader of one language: the 3D board's entry weighed 6,624,622 bytes
 * decoded and 1,790,216 on the wire, of which almost all was plan text in
 * languages that reader cannot read. Measured against the live deployment on
 * 2026-08-23; with only English static the same entry builds at 334,820.
 *
 * English is **not** here and must never be: it is {@link FALLBACK_LANGUAGE},
 * the answer when a language has no text, and a fallback that has to be
 * fetched is not a fallback.
 *
 * Written as twenty-one literal `import()` calls rather than one built from a
 * template, because a bundler can only emit a chunk for a specifier it can
 * see. A template would make Vite emit all twenty-one for every build and
 * Metro resolve none of them.
 */
const LOADERS: Partial<Record<Language, () => Promise<{ default: unknown }>>> = {
  ar: () => import('../data/plans.ar.json'),
  bn: () => import('../data/plans.bn.json'),
  de: () => import('../data/plans.de.json'),
  es: () => import('../data/plans.es.json'),
  fr: () => import('../data/plans.fr.json'),
  hi: () => import('../data/plans.hi.json'),
  ja: () => import('../data/plans.ja.json'),
  jv: () => import('../data/plans.jv.json'),
  ko: () => import('../data/plans.ko.json'),
  mr: () => import('../data/plans.mr.json'),
  ms: () => import('../data/plans.ms.json'),
  pa: () => import('../data/plans.pa.json'),
  pt: () => import('../data/plans.pt.json'),
  ru: () => import('../data/plans.ru.json'),
  ta: () => import('../data/plans.ta.json'),
  te: () => import('../data/plans.te.json'),
  tr: () => import('../data/plans.tr.json'),
  uk: () => import('../data/plans.uk.json'),
  ur: () => import('../data/plans.ur.json'),
  vi: () => import('../data/plans.vi.json'),
  zh: () => import('../data/plans.zh.json'),
};

/** What has been loaded. English is here from the first line of the module. */
const PLANS: Partial<Record<Language, Plan[]>> = { en: en as unknown as Plan[] };

/**
 * Which languages have their plan text in memory right now.
 *
 * For a server to say out loud at startup what it actually holds. The bot's
 * banner used to *assert* that twenty languages get the plans in their own
 * language; since the text is loaded on demand that sentence is only true if
 * `loadEveryLanguage` finished, and an assertion that depends on an await
 * somewhere else is a sentence waiting to be wrong. This makes it a
 * measurement.
 */
export function loadedLanguages(): Language[] {
  return Object.keys(PLANS) as Language[];
}

/**
 * Bring one language's plans into memory. Idempotent, and safe to call twice.
 *
 * The board calls this once, for the language it is about to render in, before
 * anything reads a plan. Everything that is not the board calls
 * {@link loadEveryLanguage} instead: the bot serves twenty-two languages from
 * one process and cannot await inside a command.
 */
export async function loadLanguage(locale: string): Promise<void> {
  const language = resolveLanguage(locale);
  if (PLANS[language]) return;

  const loader = LOADERS[language];
  // A language with no loader and no text is not an error here: `resolveLanguage`
  // already answers with something this module knows, and the fallback below
  // is what a caller gets.
  if (!loader) return;

  PLANS[language] = (await loader()).default as Plan[];
}

/** Every language, for a runtime that serves all of them. */
export async function loadEveryLanguage(): Promise<void> {
  await Promise.all((Object.keys(LOADERS) as Language[]).map((one) => loadLanguage(one)));
}

/**
 * How long a test hook may spend on the line above — measured, and one number
 * rather than twelve.
 *
 * `beforeAll(loadEveryLanguage)` appears TWELVE TIMES across five workspaces,
 * and every one of them was betting on vitest's 10-second default. On
 * 2026-08-28 one lost: `apps/docs/tests/render.test.ts` timed out in its hook
 * and took 167 tests with it, at a clean checkout with nothing changed. Alone
 * that whole file takes 2.56 seconds.
 *
 * It is not slow, it is starved. `bun run test` runs twelve workspaces at once,
 * each with its own vitest worker pool, and this hook reads twenty-two
 * languages of plan text off the disk — so the twelve heaviest hooks in the
 * repository all contend for the same disk and cores at the same moment. It was
 * the second failure of that exact shape in two days; the first was a test
 * deadline in `packages/content/tests/undo.test.ts`, and fixing that one alone
 * left eleven more bets outstanding.
 *
 * A minute, because the number that matters is not the honest duration but the
 * one that still fails a genuine hang while never failing a machine under load.
 * Exported so the reason lives once and the twelve call sites point at it: a
 * deadline copied twelve times is twelve things to change when the next one
 * loses.
 */
export const EVERY_LANGUAGE_MS = 60_000;

/**
 * The languages already complained about, so the complaint is made once.
 *
 * Serving English where Russian was asked for is the failure this project
 * keeps having quietly — a truncating header and a voice falling back both
 * lived for weeks because nothing said so. A caller that forgot to await is
 * told, in a log, on the first plan it asks for; a caller that is legitimately
 * on a language with no text is told once and then left alone.
 */
const complained = new Set<Language>();

/**
 * Say something, wherever there is somewhere to say it.
 *
 * This package is compiled without the DOM or Node libraries on purpose — it
 * is the one thing every runtime here shares, and naming `console` outright
 * does not typecheck under `tsconfig.src.json`. Reached through `globalThis`
 * and called only if it is there: a runtime with no console is a runtime that
 * hears nothing, which is worse than a warning and much better than a crash.
 */
function warn(message: string): void {
  const sink = (globalThis as { console?: { warn?: (said: string) => void } }).console;
  sink?.warn?.(message);
}

function textFor(language: Language): Plan[] {
  const held = PLANS[language];
  if (held) return held;

  if (LOADERS[language] && !complained.has(language)) {
    complained.add(language);
    warn(
      `[content] plans for '${language}' were not loaded; serving ${FALLBACK_LANGUAGE}. ` +
        'Await loadLanguage() for a board, or loadEveryLanguage() for a server.',
    );
  }

  return PLANS[FALLBACK_LANGUAGE] as Plan[];
}

const RULES = rulesData as Record<string, RuleChapter[]>;

/** Every plan for a language, ordered 1..72. */
export function plansFor(locale: string): Plan[] {
  return textFor(resolveLanguage(locale));
}

/**
 * One plan by number.
 *
 * @throws RangeError when `plan` is outside 1..72.
 */
export function planFor(locale: string, plan: number): Plan {
  if (!Number.isInteger(plan) || plan < 1 || plan > TOTAL_PLANS) {
    throw new RangeError(`plan must be an integer in 1..${TOTAL_PLANS}, got ${plan}`);
  }
  const found = textFor(resolveLanguage(locale)).find((p) => p.plan === plan);
  // Every language is complete, but fall back rather than throw if a future
  // rebuild ever drops one.
  return found ?? ((PLANS[FALLBACK_LANGUAGE] as Plan[]).find((p) => p.plan === plan) as Plan);
}

/** Rules chapters for a language, empty when none were translated. */
export function rulesFor(locale: string): RuleChapter[] {
  return RULES[resolveLanguage(locale)] ?? RULES[FALLBACK_LANGUAGE] ?? [];
}

/**
 * The book a reader gets, which is never empty.
 *
 * A language with no chapters is served English — as a *whole book*, not
 * chapter by chapter: half in one language and half in another is worse than
 * one a reader can at least read.
 *
 * This was written out five times: twice in the bot, twice in the mini app,
 * and its absence once in the docs. Four of those five were written in a single
 * afternoon, by one author, which is how quickly a rule spreads once it lives
 * nowhere.
 *
 * **The docs deliberately do not use it.** `apps/docs` writes a page per
 * language per chapter, and `audit-dataset.mjs` refuses a chapter written in a
 * script its language does not use — a published `/de/rules/notes.html` holding
 * English would be exactly that. A reader shown English on screen has been
 * helped; a reader handed a German URL serving English has been misled. The
 * difference is between falling back and filing wrongly.
 */
export function bookFor(locale: string): RuleChapter[] {
  return bookFrom(rulesFor(locale), rulesFor(FALLBACK_LANGUAGE));
}

/**
 * The borrow rule, over two books rather than over the whole dataset.
 *
 * `bookFor` reads `RULES`, which is every language at once — right for a server
 * and wrong for a phone, where fetching the book means fetching one language's
 * chapters and English's. A surface that has loaded exactly those two still has
 * to make the same decision about them, and a decision made twice is a decision
 * that will differ: this is the one place it is written.
 *
 * Takes no locale on purpose. Which chapters belong to whom is the caller's
 * business; what to do when one book is short is this function's.
 */
export function bookFrom(
  chapters: readonly RuleChapter[],
  english: readonly RuleChapter[],
): RuleChapter[] {
  if (chapters.length === 0) return [...english];

  // A chapter the reader's book does not have, borrowed from English and
  // marked as borrowed.
  //
  // The whole-book rule above is about a language with *nothing*, and it is
  // still right. This is a different situation and it was found rather than
  // imagined: Ukrainian, Malay and Arabic carry `online` and `foreword` — a
  // chat-moderation policy and a preface — and no chapter on the chakras,
  // because those three came through a different donor with a different table
  // of contents. Two of them have no `meaning` chapter either.
  //
  // So the choice was never "one language or two". It was "the chapter in
  // English, or no chapter at all", and a reader cannot read what is not
  // there. The order is the reader's own book first, then whatever it is
  // missing, so nothing they *do* have is displaced.
  const have = new Set(chapters.map((chapter) => chapter.slug));
  const missing = english
    .filter((chapter) => !have.has(chapter.slug))
    .map((chapter) => ({ ...chapter, borrowed: true }));

  return [...chapters, ...missing];
}

/** One rules chapter by slug, or null. */
export function ruleChapter(locale: string, slug: string): RuleChapter | null {
  return rulesFor(locale).find((c) => c.slug === slug) ?? null;
}

// How long until the next throw, in the player's language. The engine does the
// arithmetic and had the words too, in English, inside a Russian sentence.
export { formatWait } from './wait';

// A move, in a sentence. Beside the catalogue it is built from, because two
// surfaces need the same nine sentences and a tenth would be a tenth wording.
export { describeMove } from './describe';
export type { TitleOf } from './describe';

// What a language is, beyond its texts: which way it reads, what it calls
// itself, and how to keep a diagram from being reordered by a reader's script.
export {
  LANGUAGE_NAMES,
  asLeftToRight,
  couldBe,
  directionOf,
  dominantScript,
  scriptOf,
  writtenIn,
} from './languages';
export type { Script } from './languages';

// The sentences the game says about itself, as opposed to the text it teaches.
// Kept in a second file because the catalogue is prose and this one is data.
export {
  englishCatalogue,
  messageCoverage,
  answeredIn,
  messageFor,
  messageIssues,
  placeholdersIn,
  translatedLanguages,
  type LanguageCoverage,
  type Message,
  type MessageIssue,
  type MessageKey,
  type MessageParams,
  type PluralForms,
} from './messages';

/** A paragraph of a text that is a heading rather than prose. */
export interface Heading {
  /** How many hashes were written, 1 to 6. */
  level: number;
  /** What it says, without them. */
  text: string;
}

/**
 * Whether a paragraph is a heading, and what it says.
 *
 * The rules chapters write their sections as `## The second chakra
 * (Svadhisthana)` — three hundred and five of them across nineteen languages.
 * The book renders those as headings. The mini app and the phone put the
 * paragraph on the screen as text, so a reader of either met the hashes:
 * literally `## দ্বিতীয় চক্রে (স্বাধিষ্ঠান)`, markup shown to somebody who
 * never asked to see any.
 *
 * Here because three surfaces read one text and each had decided for itself
 * what a paragraph is — which is the shape this repository keeps finding, and
 * the reason `stateFromKept` and `whyNotPlayable` live in the engine rather
 * than in the app that needed them first.
 *
 * The level is the author's, not a place in anybody's document: what a surface
 * does with a level — the book adds one so the page's own title stays the
 * first — is the surface's own business.
 */
export function headingOf(paragraph: string): Heading | null {
  // The space is not required. CommonMark asks for one and seventeen headings
  // in the shipped texts have lost theirs — `##Vedanta`, `##Yoga`, `##श्रुति`,
  // `##ਪੁਰਾਣ` — every one of them a section of the glossary that the same
  // chapter in another language writes with the space. Measured before it was
  // loosened: seventeen paragraphs change meaning under this rule and all
  // seventeen are section names. Nothing else in twenty-two languages does.
  //
  // Repaired at the reader rather than in the text, because this repository
  // does not edit translations — and a missing space is not a judgement about
  // what a sentence should say.
  const found = /^(#{1,6})\s*(.*)$/.exec(paragraph.trim());
  if (!found) return null;

  const [, hashes = '', text = ''] = found;
  const said = text.trim();

  // Hashes and nothing else is a heading whose words were lost — the Turkish
  // glossary has one — and it is not a heading anybody can read. `piecesOf`
  // drops it rather than drawing the marks.
  return said === '' ? null : { level: hashes.length, text: said };
}

/** A paragraph as a reader meets it: prose, or a heading with its level. */
export interface Piece {
  /** The heading it is, or null for prose. */
  heading: Heading | null;
  /** What to draw: the prose, or the heading's own words. */
  text: string;
}

/**
 * A text as the pieces a reader meets.
 *
 * Three surfaces read these texts and each had split them for itself. The book
 * rendered headings; the mini app put every paragraph on the screen as text and
 * the phone put the whole body in one block, so a reader of either met the
 * hashes — three hundred and five of them across nineteen languages, markup
 * shown to somebody who never asked to see any.
 *
 * A paragraph that is only hashes is dropped. It is a heading whose words did
 * not survive a translation, it says nothing, and drawing `##` says less than
 * nothing.
 */
export function piecesOf(text: string): Piece[] {
  return text
    .split(/\n{2,}/)
    .flatMap(apart)
    .map((paragraph) => paragraph.trim())
    .filter((paragraph) => paragraph.length > 0)
    .filter((paragraph) => !/^#{1,6}$/.test(paragraph))
    .map((paragraph) => {
      const heading = headingOf(paragraph);
      return heading ? { heading, text: heading.text } : { heading: null, text: paragraph };
    });
}

/**
 * A block, split where a heading is written inside it.
 *
 * The blank line is not always there. Seventeen blocks — all of them Russian,
 * in `ru/chakras` and `ru/notes` — write `#### Первая чакра (Муладхара)` and
 * the paragraph it heads on the next line down, with nothing between, and
 * every surface read that as one paragraph beginning with hashes. The published
 * Russian chapter had **no headings on it at all** and four hash marks in their
 * place. Russian is one of the two languages nobody machine-translated, which
 * is why it is the one where somebody wrote it by hand this way.
 *
 * A heading is a line, not a paragraph. This is the only place that says so.
 */
function apart(block: string): string[] {
  const parts: string[] = [];
  let prose: string[] = [];

  const keep = () => {
    if (prose.length > 0) parts.push(prose.join('\n'));
    prose = [];
  };

  for (const line of block.split('\n')) {
    // A fence is not content. The Russian chakras chapter puts two paragraphs
    // of Sri Ramana Maharshi between ``` marks, and nothing here knows what a
    // fence is — so the book's inline rule for `code` matched from the third
    // backtick to the fourth and drew his words in a monospace font with two
    // stray marks on either side, on the published page. A line of backticks
    // holds no words, so dropping it loses none.
    if (/^\s*`{3,}\s*\w*\s*$/.test(line)) continue;

    if (headingOf(line) === null) {
      prose.push(line);
      continue;
    }

    keep();
    parts.push(line);
  }

  keep();
  return parts;
}

/**
 * The marks a sentence ends with, in the scripts these texts are written in.
 *
 * Derived from the texts rather than remembered. Counted over the last
 * character of every paragraph in all twenty-two languages: `.` 6,961 times,
 * `।` 1,239, `。` 854, `۔` 428, and `!`, `?` and `…` in the tens.
 *
 * It is here because it has been got wrong twice in two different places, and
 * both times the same two characters were missing. `trimToParagraph` in
 * `@leela/ai` knew `.` and `。`, so the plan text reached the companion cut
 * mid-word for every language that ends a sentence with `।` or `۔` — Hindi
 * plan 23 stopped inside `सर्वोच`. `whole`, one file over, trims the
 * companion's own reply back to the last finished sentence and knew six marks
 * without those two, so a Hindi or Urdu player read the half sentence that
 * every other language is spared. And a sweep of mine for texts ending without
 * a terminator called two hundred and ninety-eight Bengali and Hindi plans
 * broken, on the same two characters again.
 *
 * Three places, one omission. A list that has to be remembered is a list that
 * will be written short again.
 */
export const SENTENCE_ENDS = ['.', '。', '।', '۔', '!', '?', '…', '！', '？'] as const;

/** Where the last sentence in a text finishes, or -1 if none does. */
export function lastSentenceEnd(text: string, before = text.length): number {
  return Math.max(...SENTENCE_ENDS.map((mark) => text.lastIndexOf(mark, before)));
}
