/**
 * Detox, driving the app the way a player does.
 *
 * The unit suites own the rules — `@leela/engine` has 334 of them and this app
 * carries none of its own. What they cannot see is the *wiring*: whether the
 * die is connected to `advance`, whether the writing box files into the journal
 * the gate reads, whether a game survives being closed. Every defect this app
 * has given up so far was found by running it, and this is that, written down.
 *
 * **The die is not seeded for the tests, and that is deliberate.** A player
 * needs a six to enter the board, and the obvious way to make that certain is a
 * launch argument only a test passes — a code path nobody who plays the game
 * ever takes, which is the kind of door this repository does not open. So the
 * suites tap the die until the board says they are on it, with a stated bound.
 * Forty throws without a six is one run in two thousand; the bound is in the
 * helper and it fails loudly rather than hanging.
 *
 * **It cannot run in CI.** Every job here is `ubuntu-latest`, and this needs a
 * Mac, an iOS simulator, and a native build of the app — `ios/` is generated by
 * `expo prebuild` and gitignored. So it is a command a person runs, and this
 * comment is where that is said rather than in a job that would be skipped.
 *
 *   npx expo prebuild --platform ios      # once, or after changing app.json
 *   npx detox build --configuration ios.debug
 *   npx detox test  --configuration ios.debug
 */

/** @type {Detox.DetoxConfig} */
module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      config: 'e2e/jest.config.js',
    },
    jest: {
      setupTimeout: 240_000,
    },
  },
  apps: {
    'ios.debug': {
      type: 'ios.app',
      // Named after `expo.name` in app.json, which `expo prebuild --clean`
      // derives the project from. Hard-coding `Leela.app` here was wrong for a
      // day: the project is `LeelaChakra.xcodeproj` and a stale name fails as
      // "app not found", which reads like a build that never happened.
      binaryPath: 'ios/build/Build/Products/Debug-iphonesimulator/LeelaChakra.app',
      build:
        'xcodebuild -workspace ios/LeelaChakra.xcworkspace -scheme LeelaChakra ' +
        '-configuration Debug -sdk iphonesimulator -derivedDataPath ios/build ' +
        '-destination "generic/platform=iOS Simulator" build | cat',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: { type: 'iPhone 16 Pro' },
    },
  },
  configurations: {
    'ios.debug': {
      device: 'simulator',
      app: 'ios.debug',
    },
  },
};
