/**
 * Detox, driving the app the way a player does.
 *
 * The unit suites own the rules — `@leela/engine` has 334 of them and this app
 * carries none of its own. What they cannot see is the *wiring*: whether the
 * die is connected to `advance`, whether the writing box files into the journal
 * the gate reads, whether a game survives being closed. Every defect this app
 * has given up so far was found by running it, and this is that, written down.
 *
 * **The die is not seeded for the tests, and that is deliberate.** A player
 * needs a six to enter the board, and the obvious way to make that certain is a
 * launch argument only a test passes — a code path nobody who plays the game
 * ever takes, which is the kind of door this repository does not open. So the
 * suites tap the die until the board says they are on it, with a stated bound.
 * Forty throws without a six is one run in two thousand; the bound is in the
 * helper and it fails loudly rather than hanging.
 *
 * **It cannot run in CI.** Every job here is `ubuntu-latest`, and this needs a
 * Mac, an iOS simulator, and a native build of the app — `ios/` is generated by
 * `expo prebuild` and gitignored. So it is a command a person runs, and this
 * comment is where that is said rather than in a job that would be skipped.
 *
 * **And it needs port 8081 to itself.** A debug React Native build asks for its
 * bundle at the default port, baked in at compile time, and that cannot be
 * moved without rebuilding — `RCT_METRO_PORT` was tried and does not reach a
 * Debug build's runtime lookup. Another project's packager there answers with
 * its own bundle, which arrives as *unable to resolve module ./index* and reads
 * exactly like this app being broken. Two debug apps, one port: run one at a
 * time. The identifiers are separate (see `app.config.ts`) so they no longer
 * *replace* each other, which is the part that mattered.
 *
 *   npx expo prebuild --platform ios      # once, or after changing app.json
 *   npx detox build --configuration ios.debug
 *   npx detox test  --configuration ios.debug
 */

const { readdirSync } = require('node:fs');
const { join } = require('node:path');

/**
 * The scheme, found rather than named.
 *
 * `expo prebuild --clean` derives the project from `expo.name`, so it is
 * `LeelaChakra` today and whatever the app is called tomorrow — and a
 * development build is called something else again. A name written down here
 * fails as *app not found*, which reads exactly like a build that never
 * happened. `tests/identity.test.ts` learned the same thing about the bundle
 * identifier and looks the project up by extension for the same reason.
 */
const scheme = (() => {
  const ios = join(__dirname, 'ios');
  const found = readdirSync(ios).filter((entry) => entry.endsWith('.xcodeproj'));
  if (found.length !== 1) {
    throw new Error(
      `expected one .xcodeproj in ios/, found ${found.length}. Run: npm run prebuild`,
    );
  }
  return found[0].slice(0, -'.xcodeproj'.length);
})();

/** @type {Detox.DetoxConfig} */
module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      config: 'e2e/jest.config.js',
    },
    jest: {
      setupTimeout: 240_000,
    },
  },
  apps: {
    'ios.debug': {
      type: 'ios.app',
      binaryPath: `ios/build/Build/Products/Debug-iphonesimulator/${scheme}.app`,
      build:
        `xcodebuild -workspace ios/${scheme}.xcworkspace -scheme ${scheme} ` +
        '-configuration Debug -sdk iphonesimulator -derivedDataPath ios/build ' +
        '-destination "generic/platform=iOS Simulator" build | cat',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: { type: 'iPhone 16 Pro' },
    },
  },
  configurations: {
    'ios.debug': {
      device: 'simulator',
      app: 'ios.debug',
    },
  },
};
