declare module '@env' {
  export const LEELA_ID: string
  export const OPEN_AI_KEY: string
  export const APPLE: string
  export const GOOGLE: string
  export const NFT_STORAGE_API_KEY: string
  export const RALLY_API_KEY: string
  export const SENTRY_DSN: string
  export const ALCHEMY_API_KEY: string
  export const ALCHEMY_API_HTTPS: string
  export const ALCHEMY_API_WS: string
  export const PUBLIC_KEY: string
  export const PRIVATE_KEY: string
  export const CONTRACT_ADDRESS: string
  export const THE_GRAPH_API: string
  export const ID_SENDPULSE: string
  export const SECRET_SENDPULSE: string
  export const Leela_AI_RU: string
  export const Leela_AI_EN: string
  export const YANDEX_FOLDER_ID: string
  export const YANDEX_TRANSLATE_API_KEY: string
  export const EMAIL: string
  export const PASSWORD: string
}
