require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'leela' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
 
  target 'leelaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()


  post_install do |installer|
    fix_deployment_target(installer)
  end
  
  def fix_deployment_target(installer)
    return if !installer
    project = installer.pods_project
    project_deployment_target = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
  
    puts "Make sure all pods deployment target is #{project_deployment_target.green}"
    project.targets.each do |target|
      puts "  #{target.name}".blue
      target.build_configurations.each do |config|
        old_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        new_target = project_deployment_target
        next if old_target == new_target
        puts "    #{config.name}: #{old_target.yellow} -> #{new_target.green}"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = new_target
      end
    end
  end
  
end