import { describe, expect, it } from 'vitest';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * The published app's identity, which is two strings and not one.
 *
 * `MIGRATION.md` said *keep the `applicationId` and the bundle id* as though
 * they were the same value. They are not, and this app was built with one of
 * them on both platforms for two passes:
 *
 * - **iOS** is `xyz.ghashtag.dharma`, read from
 *   `leela/ios/leela.xcodeproj/project.pbxproj`, and the app on a home screen
 *   is called *Leela Chakra* — `CFBundleDisplayName` in `ios/leela/Info.plist`.
 * - **Android** is `com.leelagame`, read from `android/app/build.gradle`.
 *
 * The difference is not cosmetic. An iOS build under the wrong identifier is a
 * different application to the store, to the keychain, and to every player who
 * has the published one installed: it cannot update them, and it cannot see
 * anything they wrote.
 *
 * Asserted rather than commented, because the value that matters here is one a
 * person types once and never looks at again.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const config = JSON.parse(
  readFileSync(resolve(HERE, '..', 'app.json'), 'utf8'),
) as {
  expo: {
    name: string;
    ios: { bundleIdentifier: string };
    android: { package: string };
  };
};

describe('the app is the app that is published', () => {
  it('carries the iOS bundle identifier of the published build', () => {
    expect(config.expo.ios.bundleIdentifier).toBe('xyz.ghashtag.dharma');
  });

  it('carries the Android application id of the published build', () => {
    expect(config.expo.android.package).toBe('com.leelagame');
  });

  it('keeps them apart, which is the whole of this file', () => {
    // The defect written down as a test: one value used for both.
    expect(config.expo.ios.bundleIdentifier).not.toBe(config.expo.android.package);
  });

  it('is called what the home screen calls it', () => {
    expect(config.expo.name).toBe('Leela Chakra');
  });
});

describe('the app that installs, not the config that describes it', () => {
  /**
   * The same defect, one floor down, found by running the app rather than by
   * reading it.
   *
   * Everything above holds `app.json`. `app.json` was right — and the built
   * app on the simulator answered to **`com.leelagame`**, the *Android*
   * identifier, because `ios/` is generated by `expo prebuild` and prebuild
   * does not rewrite an identifier in a native project that already exists.
   * So the file this test reads said one thing and the artifact a player
   * installs said another, which is the shape this repository met in
   * `lib/corrections.mjs`: a check that reads the source cannot see a defect in
   * the generated file.
   *
   * `npx expo prebuild --platform ios --clean` is the repair, and it is the
   * only one — editing `project.pbxproj` would put the fix back in the
   * artifact where the next regeneration eats it.
   *
   * **Skipped when there is no native project**, which is most of the time:
   * `ios/` is gitignored, absent in CI, and 920 MB when it exists. A test that
   * silently passes on an absence is the thing this repository keeps closing,
   * so it says which of the two it did.
   */
  // Found rather than named. `--clean` regenerates the project from
  // `app.json`, so it is called `LeelaChakra.xcodeproj` today and whatever
  // `expo.name` says tomorrow — a test that hard-codes the name skips silently
  // the day somebody renames the app, which is the failure it exists to catch.
  const ios = resolve(HERE, '..', 'ios');
  const found = existsSync(ios)
    ? readdirSync(ios).filter((entry) => entry.endsWith('.xcodeproj'))
    : [];
  const project = found.length === 1 ? join(ios, found[0]!, 'project.pbxproj') : '';
  const prebuilt = project !== '' && existsSync(project);

  it.skipIf(!prebuilt)('is built under the identifier app.json states', () => {
    const pbxproj = readFileSync(project, 'utf8');
    const identifiers = new Set(
      [...pbxproj.matchAll(/PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);/g)].map((one) =>
        one[1]!.trim().replace(/^"|"$/g, ''),
      ),
    );

    expect(identifiers.size, 'one app, one identifier').toBe(1);

    // Either identity, and nothing else. `ios/` is generated for whichever
    // variant was asked for — `npm run prebuild` asks for the development one —
    // so the artifact carries `…dharma` or `…dharma.dev`, and a third value
    // means the project was built from something other than this config.
    const shipped = config.expo.ios.bundleIdentifier;
    expect([shipped, `${shipped}.dev`]).toContain([...identifiers][0]);

    // The one that mattered: the Android identifier is not an iOS identity, and
    // the app installed under it for a day.
    expect([...identifiers][0], 'never the Android one').not.toBe(config.expo.android.package);
    expect([...identifiers][0]).not.toBe(`${config.expo.android.package}.dev`);
  });

  it('says out loud whether it looked', () => {
    // Not a check of the app — a check of this file. `ios/` is generated and
    // usually absent, and the run above is skipped when it is. This asserts
    // that the skip is a decision with a reason rather than a silent nothing.
    expect(typeof prebuilt).toBe('boolean');
    if (!prebuilt) {
      console.log('identity: no ios/ — run `npx expo prebuild --platform ios` to check the artifact');
    }
  });
});

describe('a debug build is not the published application', () => {
  /**
   * Two apps with one identifier are one app to iOS. Installing this port on a
   * simulator replaced the published app twice in a single day, and on a real
   * phone it would have replaced it on somebody's home screen and taken their
   * game with it — the install simply succeeds and the other one is gone, with
   * nothing to warn anybody.
   *
   * So `app.config.ts` appends `.dev` when `APP_VARIANT=development`, which is
   * what every script that builds for a simulator sets. What is asserted is the
   * shape: the shipped identity is untouched, the development one differs on
   * both platforms, and the default is the safe one.
   */
  const variant = (development: boolean) => {
    const expo = config.expo;
    if (!development) return expo;
    return {
      ...expo,
      name: `${expo.name} (dev)`,
      ios: { ...expo.ios, bundleIdentifier: `${expo.ios.bundleIdentifier}.dev` },
      android: { ...expo.android, package: `${expo.android.package}.dev` },
    };
  };

  it('leaves the shipped identity exactly as app.json states it', () => {
    // The published app's own, on both platforms. A release build sets no
    // variable and must get this.
    expect(variant(false).ios.bundleIdentifier).toBe('xyz.ghashtag.dharma');
    expect(variant(false).android.package).toBe('com.leelagame');
    expect(variant(false).name).toBe('Leela Chakra');
  });

  it('gives a development build an identifier of its own, on both platforms', () => {
    const dev = variant(true);

    expect(dev.ios.bundleIdentifier).not.toBe(config.expo.ios.bundleIdentifier);
    expect(dev.android.package).not.toBe(config.expo.android.package);
  });

  it('keeps the two apart on the home screen as well', () => {
    // Two icons with one name is a person launching the wrong one and reporting
    // a defect in the other.
    expect(variant(true).name).not.toBe(variant(false).name);
  });

  it('is the safe way round', () => {
    // Forgetting the variable cannot make a release the wrong application —
    // only a debug build the right one, which is caught the moment somebody
    // looks at what installed.
    expect(variant(false).ios.bundleIdentifier).toBe(config.expo.ios.bundleIdentifier);
  });

  it('every script that builds for a simulator asks for the variant', () => {
    // The rule that makes the rest of this true. A script that builds and
    // forgets it installs over the published app, silently.
    const manifest = JSON.parse(
      readFileSync(resolve(HERE, '..', 'package.json'), 'utf8'),
    ) as { scripts: Record<string, string> };

    for (const [name, command] of Object.entries(manifest.scripts)) {
      const builds = /expo run:|detox (build|test)|expo prebuild/.test(command);
      if (!builds) continue;
      expect(command, `${name} builds without APP_VARIANT`).toContain('APP_VARIANT=development');
    }
  });
});
