import { describe, expect, it, vi } from 'vitest';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ExpoConfig } from 'expo/config';
// The suffix, from the file that applies it. Typing '.dev' here would be a
// second definition of the one string this file exists to be sure about.
import { DEV_SUFFIX } from '../app.config';

/**
 * The published app's identity, which is two strings and not one.
 *
 * `MIGRATION.md` said *keep the `applicationId` and the bundle id* as though
 * they were the same value. They are not, and this app was built with one of
 * them on both platforms for two passes:
 *
 * - **iOS** is `xyz.ghashtag.dharma`, read from
 *   `leela/ios/leela.xcodeproj/project.pbxproj`, and the app on a home screen
 *   is called *Leela Chakra* — `CFBundleDisplayName` in `ios/leela/Info.plist`.
 * - **Android** is `com.leelagame`, read from `android/app/build.gradle`.
 *
 * The difference is not cosmetic. An iOS build under the wrong identifier is a
 * different application to the store, to the keychain, and to every player who
 * has the published one installed: it cannot update them, and it cannot see
 * anything they wrote.
 *
 * Asserted rather than commented, because the value that matters here is one a
 * person types once and never looks at again.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const config = JSON.parse(
  readFileSync(resolve(HERE, '..', 'app.json'), 'utf8'),
) as {
  expo: {
    name: string;
    ios: { bundleIdentifier: string };
    android: { package: string };
  };
};

describe('the app is the app that is published', () => {
  it('carries the iOS bundle identifier of the published build', () => {
    expect(config.expo.ios.bundleIdentifier).toBe('xyz.ghashtag.dharma');
  });

  it('carries the Android application id of the published build', () => {
    expect(config.expo.android.package).toBe('com.leelagame');
  });

  it('keeps them apart, which is the whole of this file', () => {
    // The defect written down as a test: one value used for both.
    expect(config.expo.ios.bundleIdentifier).not.toBe(config.expo.android.package);
  });

  it('is called what the home screen calls it', () => {
    expect(config.expo.name).toBe('Leela Chakra');
  });
});

describe('the app that installs, not the config that describes it', () => {
  /**
   * The same defect, one floor down, found by running the app rather than by
   * reading it.
   *
   * Everything above holds `app.json`. `app.json` was right — and the built
   * app on the simulator answered to **`com.leelagame`**, the *Android*
   * identifier, because `ios/` is generated by `expo prebuild` and prebuild
   * does not rewrite an identifier in a native project that already exists.
   * So the file this test reads said one thing and the artifact a player
   * installs said another, which is the shape this repository met in
   * `lib/corrections.mjs`: a check that reads the source cannot see a defect in
   * the generated file.
   *
   * `npx expo prebuild --platform ios --clean` is the repair, and it is the
   * only one — editing `project.pbxproj` would put the fix back in the
   * artifact where the next regeneration eats it.
   *
   * **Skipped when there is no native project**, which is most of the time:
   * `ios/` is gitignored, absent in CI, and 920 MB when it exists. A test that
   * silently passes on an absence is the thing this repository keeps closing,
   * so it says which of the two it did.
   */
  // Found rather than named. `--clean` regenerates the project from
  // `app.json`, so it is called `LeelaChakra.xcodeproj` today and whatever
  // `expo.name` says tomorrow — a test that hard-codes the name skips silently
  // the day somebody renames the app, which is the failure it exists to catch.
  const ios = resolve(HERE, '..', 'ios');
  const found = existsSync(ios)
    ? readdirSync(ios).filter((entry) => entry.endsWith('.xcodeproj'))
    : [];
  const project = found.length === 1 ? join(ios, found[0]!, 'project.pbxproj') : '';
  const prebuilt = project !== '' && existsSync(project);

  it.skipIf(!prebuilt)('is built under the identifier app.json states', () => {
    const pbxproj = readFileSync(project, 'utf8');
    const identifiers = new Set(
      [...pbxproj.matchAll(/PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);/g)].map((one) =>
        one[1]!.trim().replace(/^"|"$/g, ''),
      ),
    );

    expect(identifiers.size, 'one app, one identifier').toBe(1);

    // Either identity, and nothing else. `ios/` is generated for whichever
    // variant was asked for — `npm run prebuild` asks for the development one —
    // so the artifact carries `…dharma` or `…dharma.dev`, and a third value
    // means the project was built from something other than this config.
    const shipped = config.expo.ios.bundleIdentifier;
    expect([shipped, `${shipped}${DEV_SUFFIX}`]).toContain([...identifiers][0]);

    // The one that mattered: the Android identifier is not an iOS identity, and
    // the app installed under it for a day.
    expect([...identifiers][0], 'never the Android one').not.toBe(config.expo.android.package);
    expect([...identifiers][0]).not.toBe(`${config.expo.android.package}${DEV_SUFFIX}`);
  });

  it('says out loud whether it looked', () => {
    // Not a check of the app — a check of this file. `ios/` is generated and
    // usually absent, and the run above is skipped when it is. This asserts
    // that the skip is a decision with a reason rather than a silent nothing.
    expect(typeof prebuilt).toBe('boolean');
    if (!prebuilt) {
      console.log('identity: no ios/ — run `npx expo prebuild --platform ios` to check the artifact');
    }
  });
});

describe('a debug build is not the published application', () => {
  /**
   * Two apps with one identifier are one app to iOS. Installing this port on a
   * simulator replaced the published app twice in a single day, and on a real
   * phone it would have replaced it on somebody's home screen and taken their
   * game with it — the install simply succeeds and the other one is gone, with
   * nothing to warn anybody.
   *
   * So `app.config.ts` appends `.dev` when `APP_VARIANT=development`, which is
   * what every script that builds for a simulator sets. What is asserted is the
   * shape: the shipped identity is untouched, the development one differs on
   * both platforms, and the default is the safe one.
   *
   * **AND FOR TWO PASSES NONE OF THAT COULD FAIL**, which is worth more space
   * than the rule itself, because it is the failure mode the page below this one
   * spends itself naming and this block was an instance of it.
   *
   * The four cases ran against a `variant(development: boolean)` helper written
   * *here*, in this file — a hand copy of `app.config.ts`'s eleven lines. It
   * built `${name} (dev)` and appended `.dev` to both identifiers, and it was
   * correct. It was also not the code that builds the app. Measured on the day
   * this was rewritten:
   *
   * - `identity.test.ts` imported `vitest` and three node builtins, and nothing
   *   else. Nothing in the repository imported `./app.config` at all.
   * - `tsc --noEmit --listFiles` did not list `app.config.ts` in either mobile
   *   program. Counted rather than eyeballed, over the committed configs and
   *   the committed version of this file: `grep -c` answered 0 for
   *   `tsconfig.json` and 0 for `tsconfig.src.json`. It answers 1 and 0 now,
   *   and the 0 is deliberate — see the comment on the `include` entry.
   * - `npx eslint apps/mobile/app.config.ts` answered *File ignored because no
   *   matching configuration was supplied*, and exited 0.
   *
   * So deleting the `.dev` suffix from the real file left `bun run verify`,
   * every audit, ESLint and knip green — and the next simulator build would
   * install over the published app. The copies had already started to drift:
   * this helper read `expo.ios.bundleIdentifier` where the real file reads
   * `expo.ios?.bundleIdentifier`.
   *
   * The repair is not a better copy. The cases below `await import`
   * `../app.config` with `APP_VARIANT` set and unset around a `vi.resetModules`,
   * and call the default export — the same function Expo calls. What they assert
   * is the *relationship* between the two identities rather than the strings a
   * particular implementation produces, and `DEV_SUFFIX` is imported rather than
   * typed, so the suffix has exactly one definition in the repository.
   */

  /**
   * The config Expo would be handed for a given `APP_VARIANT`.
   *
   * `app.config.ts` reads the variable at module scope — `const DEVELOPMENT =
   * process.env.APP_VARIANT === 'development'` — so the variable has to be in
   * place *before* the module is evaluated. Hence `vi.resetModules()` around a
   * dynamic import rather than a static one: a static import would be evaluated
   * once, at whatever the environment happened to be when this file loaded, and
   * every case after the first would read a stale decision.
   *
   * The previous value is put back in a `finally`, because this mutates a real
   * process global that the rest of the run shares.
   */
  const asBuilt = async (variant: string | undefined): Promise<ExpoConfig> => {
    const before = process.env.APP_VARIANT;
    if (variant === undefined) delete process.env.APP_VARIANT;
    else process.env.APP_VARIANT = variant;

    vi.resetModules();
    try {
      const { default: configure } = await import('../app.config');
      return configure();
    } finally {
      if (before === undefined) delete process.env.APP_VARIANT;
      else process.env.APP_VARIANT = before;
      vi.resetModules();
    }
  };

  it('leaves the shipped identity exactly as app.json states it', async () => {
    // The published app's own, on both platforms. A release build sets no
    // variable and must get this.
    //
    // Stated against `app.json` rather than against the three literals, which
    // are pinned once at the top of this file: a second copy of them here would
    // be the same mistake as the helper this replaced, one value smaller.
    const release = await asBuilt(undefined);

    expect(release.ios?.bundleIdentifier).toBe(config.expo.ios.bundleIdentifier);
    expect(release.android?.package).toBe(config.expo.android.package);
    expect(release.name).toBe(config.expo.name);
  });

  it('gives a development build an identifier of its own, on both platforms', async () => {
    const dev = await asBuilt('development');

    expect(dev.ios?.bundleIdentifier).not.toBe(config.expo.ios.bundleIdentifier);
    expect(dev.android?.package).not.toBe(config.expo.android.package);

    // And what separates them is the one suffix this repository declares, read
    // from the file that applies it. The two lines above are the load-bearing
    // ones — *different at all* is the property that keeps a debug build off a
    // player's home screen — and these two say the difference is a deliberate
    // suffix rather than any string that happens not to match.
    expect(dev.ios?.bundleIdentifier).toBe(`${config.expo.ios.bundleIdentifier}${DEV_SUFFIX}`);
    expect(dev.android?.package).toBe(`${config.expo.android.package}${DEV_SUFFIX}`);
  });

  it('keeps the two apart on the home screen as well', async () => {
    // Two icons with one name is a person launching the wrong one and reporting
    // a defect in the other.
    const [dev, release] = [await asBuilt('development'), await asBuilt(undefined)];

    expect(dev.name).not.toBe(release.name);
  });

  it('is the safe way round', async () => {
    // Forgetting the variable cannot make a release the wrong application —
    // only a debug build the right one, which is caught the moment somebody
    // looks at what installed.
    //
    // Asserted over the *absence* and over values that are not the one word the
    // build scripts set, because the direction is the claim: only an exact
    // `development` may move the identity. An implementation that opted out on
    // `production` instead of in on `development` would pass the case above and
    // fail here, which is the whole difference between a release that is the
    // published app and one that is not.
    for (const nothing of [undefined, '', 'Development', 'developement', 'production']) {
      const built = await asBuilt(nothing);

      expect(built.ios?.bundleIdentifier, `APP_VARIANT=${String(nothing)}`).toBe(
        config.expo.ios.bundleIdentifier,
      );
      expect(built.android?.package, `APP_VARIANT=${String(nothing)}`).toBe(
        config.expo.android.package,
      );
      expect(built.name, `APP_VARIANT=${String(nothing)}`).toBe(config.expo.name);
    }
  });

  /**
   * The shape that matters here is a loop that can run zero times.
   *
   * The rule below — a script that builds for a simulator must set
   * `APP_VARIANT=development` — is asserted over a collection that is **not a
   * literal**. It is a regex matched against free-text shell commands, and the
   * vocabulary of those commands belongs to expo and detox rather than to this
   * repository. `expo run:ios` becoming `expo run --platform ios`, `detox build`
   * becoming `detox-cli build`, or a move to `eas build` each remove matches
   * without anybody editing this file. At the limit the set is empty, the body
   * of the loop never executes, and Vitest reports a green test that checked
   * nothing — the failure mode this repository has named for itself, and the
   * one sitting between a rename and a wiped player.
   *
   * So the load-bearing assertion is the emptiness one, not the ones inside the
   * loop. `expect(builders.length).toBeGreaterThan(0)` is the only line here
   * that can notice that the world moved on; the per-command assertions can
   * only speak about commands that were found. The claim is *this check found
   * work to do*, deliberately not *this check found exactly this work*: the
   * count is not pinned and the names are not enumerated, because a guard
   * calibrated to today's manifest fails on the next legitimate script and gets
   * deleted rather than obeyed.
   *
   * The pattern is not new to this file — `says out loud whether it looked`,
   * one describe up, does the same for a skip. It was simply not carried down.
   */
  it('every script that builds for a simulator asks for the variant', () => {
    // The rule that makes the rest of this true. A script that builds and
    // forgets it installs over the published app, silently.
    const manifest = JSON.parse(
      readFileSync(resolve(HERE, '..', 'package.json'), 'utf8'),
    ) as { scripts: Record<string, string> };

    const BUILDS = /expo run:|detox (build|test)|expo prebuild/;
    const builders = Object.entries(manifest.scripts).filter(([, command]) =>
      BUILDS.test(command),
    );

    expect(
      builders.length,
      'no script matched -- the build-command shapes have moved, and this test was about to pass by checking nothing',
    ).toBeGreaterThan(0);

    for (const [name, command] of builders) {
      expect(command, `${name} builds without APP_VARIANT`).toContain('APP_VARIANT=development');
    }
  });
});
